os: linux
language: node_js
node_js:
  - "14"
dist: trusty

before_script:
  - npm install -g @angular/cli

script:
  # - ng lint
<<<<<<< Updated upstream
  - ng build --prod --base-href http://trade-project-frontend.s3-website.eu-central-1.amazonaws.com
  - ls 
=======
#  - ng build --prod --base-href http://trade-project-frontend.s3-website-eu-west-1.amazonaws.com
  - ng build --prod --base-href http://trade-project-frontend.s3-website.eu-central-1.amazonaws.com
  - ls
>>>>>>> Stashed changes
  - ls dist

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "trade-project-frontend"
  region: "eu-central-1"
  skip_cleanup: true
  local_dir: dist/
  on:
    branch: main

